### ISSUE TITLE
Have the ability to exclude the self vote address from the configured sharing %

### ISSUE THREAD

**Issue by sgdias** [dakk/lisk-pool3#10]
Currently the self vote weight counts for the distribution, it would be nice having the ability to exclude so pool administrators have the chance to do a fair marketing of the sharing %.

**Comment by dakk** [comment]
> Currently the self vote weight counts for the distribution, it would be nice having the ability to exclude so pool administrators have the chance to do a fair marketing of the sharing %.

It is already implemented; the config file has a ```includeSelfStake``` flag, default false. When false, selfstake is not considered in the distribution.
