### ISSUE TITLE
the --only-update option is not taking effect

### ISSUE THREAD

**Issue by sgdias** [dakk/lisk-pool3#12]
after executing "python3 liskpool3.py --only-update"  the following happens:

- poollogs.json does not reflect pending payments, they are all 0, although the accumulated reward for voters is added to the history as rewards paid.
- payments.sh file is created, why is created if the execution was only for updating pendings ?

**Comment by przemerr** [comment]
i can confirm the issue, the workaround is just to set `--min-payout 100000` or any high enough number

**Comment by dakk** [comment]
forgot a global, fixed
