### ISSUE TITLE
Prevent a transaction to be executed twice

### ISSUE THREAD

**Issue by sgdias** [dakk/lisk-pool3#9]
Currently it's possible to broadcast/execute txs that were already executed.

**Comment by dakk** [comment]
> Currently it's possible to broadcast/execute txs that were already executed.

Can you explain how? By running payments file twice?

**Comment by sgdias** [comment]
yes, exactly, just some mechanism to avoid any miss execution, I guess there is no need to track each txid as long it's not possible to execute same payments file twice.

**Comment by dakk** [comment]
do you have any suggestion for this? removing the file could be not a good idea

**Comment by dakk** [comment]
After execution the file is renamed to "_filename.sh_done"
